config/routes.rb
Rails.application.routes.draw do
  resources :pruebas
  resources :anteproyectos
  devise_for :users
  get 'home/index'

  root to: 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/anteproyecto.rb
class Anteproyecto < ApplicationRecord
end

app/controllers/anteproyectos_controller.rb
class AnteproyectosController < ApplicationController
  before_action :set_anteproyecto, only: [:show, :edit, :update, :destroy]

  # GET /anteproyectos
  # GET /anteproyectos.json
  def index
    @anteproyectos = Anteproyecto.all
  end

  # GET /anteproyectos/1
  # GET /anteproyectos/1.json
  def show
  end

  # GET /anteproyectos/new
  def new
    @anteproyecto = Anteproyecto.new
  end

  # GET /anteproyectos/1/edit
  def edit
  end

  # POST /anteproyectos
  # POST /anteproyectos.json
  def create
    @anteproyecto = Anteproyecto.new(anteproyecto_params)

    respond_to do |format|
      if @anteproyecto.save
        format.html { redirect_to @anteproyecto, notice: 'Anteproyecto was successfully created.' }
        format.json { render :show, status: :created, location: @anteproyecto }
      else
        format.html { render :new }
        format.json { render json: @anteproyecto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /anteproyectos/1
  # PATCH/PUT /anteproyectos/1.json
  def update
    respond_to do |format|
      if @anteproyecto.update(anteproyecto_params)
        format.html { redirect_to @anteproyecto, notice: 'Anteproyecto was successfully updated.' }
        format.json { render :show, status: :ok, location: @anteproyecto }
      else
        format.html { render :edit }
        format.json { render json: @anteproyecto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /anteproyectos/1
  # DELETE /anteproyectos/1.json
  def destroy
    @anteproyecto.destroy
    respond_to do |format|
      format.html { redirect_to anteproyectos_url, notice: 'Anteproyecto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_anteproyecto
      @anteproyecto = Anteproyecto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def anteproyecto_params
      params.require(:anteproyecto).permit(:nombre, :objetivo, :justificacion, :cronograma, :descripcionactividad, :nombreempresa, :direccionempresa, :telefonoempresa, :estatus)
    end
end

app/helpers/anteproyectos_helper.rb
module AnteproyectosHelper
end

app/views/anteproyectos/_form.html.erb
<%= form_for(anteproyecto) do |f| %>
  <% if anteproyecto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(anteproyecto.errors.count, "error") %> prohibited this anteproyecto from being saved:</h2>

      <ul>
      <% anteproyecto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %>
    <%= f.text_field :nombre %>
  </div>

  <div class="field">
    <%= f.label :objetivo %>
    <%= f.text_field :objetivo %>
  </div>

  <div class="field">
    <%= f.label :justificacion %>
    <%= f.text_field :justificacion %>
  </div>

  <div class="field">
    <%= f.label :cronograma %>
    <%= f.text_field :cronograma %>
  </div>

  <div class="field">
    <%= f.label :descripcionactividad %>
    <%= f.text_field :descripcionactividad %>
  </div>

  <div class="field">
    <%= f.label :nombreempresa %>
    <%= f.text_field :nombreempresa %>
  </div>

  <div class="field">
    <%= f.label :direccionempresa %>
    <%= f.text_field :direccionempresa %>
  </div>

  <div class="field">
    <%= f.label :telefonoempresa %>
    <%= f.text_field :telefonoempresa %>
  </div>

  <div class="field">
    <%= f.label :estatus %>
    <%= f.text_field :estatus %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/anteproyectos/edit.html.erb
<h1>Editing Anteproyecto</h1>

<%= render 'form', anteproyecto: @anteproyecto %>

<%= link_to 'Show', @anteproyecto %> |
<%= link_to 'Back', anteproyectos_path %>

app/views/anteproyectos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Anteproyectos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Objetivo</th>
      <th>Justificacion</th>
      <th>Cronograma</th>
      <th>Descripcionactividad</th>
      <th>Nombreempresa</th>
      <th>Direccionempresa</th>
      <th>Telefonoempresa</th>
      <th>Estatus</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @anteproyectos.each do |anteproyecto| %>
      <tr>
        <td><%= anteproyecto.nombre %></td>
        <td><%= anteproyecto.objetivo %></td>
        <td><%= anteproyecto.justificacion %></td>
        <td><%= anteproyecto.cronograma %></td>
        <td><%= anteproyecto.descripcionactividad %></td>
        <td><%= anteproyecto.nombreempresa %></td>
        <td><%= anteproyecto.direccionempresa %></td>
        <td><%= anteproyecto.telefonoempresa %></td>
        <td><%= anteproyecto.estatus %></td>
        <td><%= link_to 'Show', anteproyecto %></td>
        <td><%= link_to 'Edit', edit_anteproyecto_path(anteproyecto) %></td>
        <td><%= link_to 'Destroy', anteproyecto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Anteproyecto', new_anteproyecto_path %>

app/views/anteproyectos/new.html.erb
<h1>New Anteproyecto</h1>

<%= render 'form', anteproyecto: @anteproyecto %>

<%= link_to 'Back', anteproyectos_path %>

app/views/anteproyectos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @anteproyecto.nombre %>
</p>

<p>
  <strong>Objetivo:</strong>
  <%= @anteproyecto.objetivo %>
</p>

<p>
  <strong>Justificacion:</strong>
  <%= @anteproyecto.justificacion %>
</p>

<p>
  <strong>Cronograma:</strong>
  <%= @anteproyecto.cronograma %>
</p>

<p>
  <strong>Descripcionactividad:</strong>
  <%= @anteproyecto.descripcionactividad %>
</p>

<p>
  <strong>Nombreempresa:</strong>
  <%= @anteproyecto.nombreempresa %>
</p>

<p>
  <strong>Direccionempresa:</strong>
  <%= @anteproyecto.direccionempresa %>
</p>

<p>
  <strong>Telefonoempresa:</strong>
  <%= @anteproyecto.telefonoempresa %>
</p>

<p>
  <strong>Estatus:</strong>
  <%= @anteproyecto.estatus %>
</p>

<%= link_to 'Edit', edit_anteproyecto_path(@anteproyecto) %> |
<%= link_to 'Back', anteproyectos_path %>